version: '3.7'

services:
  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: joel
      POSTGRES_PASSWORD: 123123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - inner-network
  
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379" 
    networks:
      - inner-network
  
  rails:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
    restart: always
    command: ./scripts/dev-docker-entrypoint.sh
    networks:
      - inner-network
    depends_on:
      - db
      - redis

volumes:
  db-data:

networks:
  inner-network:
    driver: bridge