default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['CHUNIN_PG_DBNAME'] %>
  username: <%= ENV['CHUNIN_PG_USERNAME'] %>
  password: <%= ENV['CHUNIN_PG_PASS'] %>
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
