default: &default
  adapter: postgresql
  encoding: unicode
  database: 'postgres'
  username: 'joel'
  password: '123123'
  host: db
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  adapter: sqlite3
  database: db/test.db

production:
  <<: *default
